---

inherit_from:
  - https://raw.githubusercontent.com/thoughtbot/guides/master/style/ruby/.rubocop.yml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
Metrics/BlockLength:
  Exclude:
    - spec/**/* # copied from the inherited file
    - config/environments/*.rb
Layout/LineLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
Layout/DotPosition:
  EnforcedStyle: leading
Rails/Date:
  Enabled: true
  EnforcedStyle: flexible
Rails/TimeZone:
  Enabled: true
  EnforcedStyle: flexible
